name: RandomChest
version: ${project.version}
main: com.ceylon.randomchest.RandomChestPlugin
commands:
  랜던상자:
    description: 'This is RandomChest Command.'
    usage: 'Usage: /랜덤상자 도움말'
    aliases: [randomchest, rc]
